// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: agent/v1/agent.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RegisterHostRequest contains information sent during initial registration
type RegisterHostRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	RegistrationToken string                 `protobuf:"bytes,1,opt,name=registration_token,json=registrationToken,proto3" json:"registration_token,omitempty"` // The registration token from CreateAgent
	Hostname          string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	IpAddressV4       string                 `protobuf:"bytes,3,opt,name=ip_address_v4,json=ipAddressV4,proto3" json:"ip_address_v4,omitempty"`
	IpAddressV6       string                 `protobuf:"bytes,4,opt,name=ip_address_v6,json=ipAddressV6,proto3" json:"ip_address_v6,omitempty"`
	Platform          string                 `protobuf:"bytes,5,opt,name=platform,proto3" json:"platform,omitempty"`                                      // gopsutil Platform: distro name ("fedora", "ubuntu", "macos")
	PlatformVersion   string                 `protobuf:"bytes,6,opt,name=platform_version,json=platformVersion,proto3" json:"platform_version,omitempty"` // gopsutil PlatformVersion: "43", "22.04"
	PlatformFamily    string                 `protobuf:"bytes,7,opt,name=platform_family,json=platformFamily,proto3" json:"platform_family,omitempty"`    // gopsutil PlatformFamily: "rhel", "debian"
	KernelArch        string                 `protobuf:"bytes,8,opt,name=kernel_arch,json=kernelArch,proto3" json:"kernel_arch,omitempty"`                // gopsutil KernelArch: "aarch64", "x86_64"
	KernelVersion     string                 `protobuf:"bytes,9,opt,name=kernel_version,json=kernelVersion,proto3" json:"kernel_version,omitempty"`       // gopsutil KernelVersion: "6.17.1-300.fc43.aarch64"
	Timestamp         int64                  `protobuf:"varint,10,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                                  // Unix timestamp in seconds (for anti-replay)
	// Environment detection
	EnvironmentType      string `protobuf:"bytes,11,opt,name=environment_type,json=environmentType,proto3" json:"environment_type,omitempty"`                // "physical", "physical_with_containers", "vm", "vm_with_containers", "container"
	VirtualizationSystem string `protobuf:"bytes,12,opt,name=virtualization_system,json=virtualizationSystem,proto3" json:"virtualization_system,omitempty"` // gopsutil VirtualizationSystem: "kvm", "vmware", "xen" (empty if physical)
	ContainerRuntime     string `protobuf:"bytes,13,opt,name=container_runtime,json=containerRuntime,proto3" json:"container_runtime,omitempty"`             // "docker", "lxc", "podman", "kubernetes" (empty if not in container)
	// Existing agent UUID (for re-registration without creating new agent)
	// If provided and exists in DB, the agent will be reactivated instead of creating a new one
	ExistingAgentUuid string `protobuf:"bytes,14,opt,name=existing_agent_uuid,json=existingAgentUuid,proto3" json:"existing_agent_uuid,omitempty"` // UUID from /var/lib/watchflare/agent.uuid (empty if first registration)
	AgentVersion      string `protobuf:"bytes,15,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`                  // Agent binary version (e.g. "0.27.3"), set via ldflags
	// Additional gopsutil fields
	Os                 string  `protobuf:"bytes,16,opt,name=os,proto3" json:"os,omitempty"`                                                           // gopsutil OS: "linux", "darwin", "windows"
	VirtualizationRole string  `protobuf:"bytes,17,opt,name=virtualization_role,json=virtualizationRole,proto3" json:"virtualization_role,omitempty"` // gopsutil VirtualizationRole: "guest", "host" (empty if physical)
	HostId             string  `protobuf:"bytes,18,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`                                     // gopsutil HostID: unique OS-provided UUID
	CpuModelName       string  `protobuf:"bytes,19,opt,name=cpu_model_name,json=cpuModelName,proto3" json:"cpu_model_name,omitempty"`                 // gopsutil cpu.InfoStat.ModelName: "Apple M4 Max", "Intel Xeon E5-2690"
	CpuPhysicalCount   int32   `protobuf:"varint,20,opt,name=cpu_physical_count,json=cpuPhysicalCount,proto3" json:"cpu_physical_count,omitempty"`    // gopsutil cpu.Counts(false): physical core count
	CpuLogicalCount    int32   `protobuf:"varint,21,opt,name=cpu_logical_count,json=cpuLogicalCount,proto3" json:"cpu_logical_count,omitempty"`       // gopsutil cpu.Counts(true): logical thread count
	CpuMhz             float64 `protobuf:"fixed64,22,opt,name=cpu_mhz,json=cpuMhz,proto3" json:"cpu_mhz,omitempty"`                                   // gopsutil cpu.InfoStat.Mhz: base frequency
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RegisterHostRequest) Reset() {
	*x = RegisterHostRequest{}
	mi := &file_agent_v1_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterHostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterHostRequest) ProtoMessage() {}

func (x *RegisterHostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterHostRequest.ProtoReflect.Descriptor instead.
func (*RegisterHostRequest) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterHostRequest) GetRegistrationToken() string {
	if x != nil {
		return x.RegistrationToken
	}
	return ""
}

func (x *RegisterHostRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *RegisterHostRequest) GetIpAddressV4() string {
	if x != nil {
		return x.IpAddressV4
	}
	return ""
}

func (x *RegisterHostRequest) GetIpAddressV6() string {
	if x != nil {
		return x.IpAddressV6
	}
	return ""
}

func (x *RegisterHostRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *RegisterHostRequest) GetPlatformVersion() string {
	if x != nil {
		return x.PlatformVersion
	}
	return ""
}

func (x *RegisterHostRequest) GetPlatformFamily() string {
	if x != nil {
		return x.PlatformFamily
	}
	return ""
}

func (x *RegisterHostRequest) GetKernelArch() string {
	if x != nil {
		return x.KernelArch
	}
	return ""
}

func (x *RegisterHostRequest) GetKernelVersion() string {
	if x != nil {
		return x.KernelVersion
	}
	return ""
}

func (x *RegisterHostRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *RegisterHostRequest) GetEnvironmentType() string {
	if x != nil {
		return x.EnvironmentType
	}
	return ""
}

func (x *RegisterHostRequest) GetVirtualizationSystem() string {
	if x != nil {
		return x.VirtualizationSystem
	}
	return ""
}

func (x *RegisterHostRequest) GetContainerRuntime() string {
	if x != nil {
		return x.ContainerRuntime
	}
	return ""
}

func (x *RegisterHostRequest) GetExistingAgentUuid() string {
	if x != nil {
		return x.ExistingAgentUuid
	}
	return ""
}

func (x *RegisterHostRequest) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *RegisterHostRequest) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *RegisterHostRequest) GetVirtualizationRole() string {
	if x != nil {
		return x.VirtualizationRole
	}
	return ""
}

func (x *RegisterHostRequest) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *RegisterHostRequest) GetCpuModelName() string {
	if x != nil {
		return x.CpuModelName
	}
	return ""
}

func (x *RegisterHostRequest) GetCpuPhysicalCount() int32 {
	if x != nil {
		return x.CpuPhysicalCount
	}
	return 0
}

func (x *RegisterHostRequest) GetCpuLogicalCount() int32 {
	if x != nil {
		return x.CpuLogicalCount
	}
	return 0
}

func (x *RegisterHostRequest) GetCpuMhz() float64 {
	if x != nil {
		return x.CpuMhz
	}
	return 0
}

// RegisterHostResponse is sent back after successful registration
type RegisterHostResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	AgentId       string                 `protobuf:"bytes,3,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`          // UUID of the host
	AgentKey      string                 `protobuf:"bytes,4,opt,name=agent_key,json=agentKey,proto3" json:"agent_key,omitempty"`       // Key for authenticating future requests
	CaCert        string                 `protobuf:"bytes,5,opt,name=ca_cert,json=caCert,proto3" json:"ca_cert,omitempty"`             // CA certificate in PEM format for TLS verification
	ServerName    string                 `protobuf:"bytes,6,opt,name=server_name,json=serverName,proto3" json:"server_name,omitempty"` // TLS SNI server name for backend verification (e.g., "watchflare")
	Reactivated   bool                   `protobuf:"varint,7,opt,name=reactivated,proto3" json:"reactivated,omitempty"`                // True if existing agent was reactivated (UUID reused), false if new registration
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterHostResponse) Reset() {
	*x = RegisterHostResponse{}
	mi := &file_agent_v1_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterHostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterHostResponse) ProtoMessage() {}

func (x *RegisterHostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterHostResponse.ProtoReflect.Descriptor instead.
func (*RegisterHostResponse) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterHostResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterHostResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RegisterHostResponse) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *RegisterHostResponse) GetAgentKey() string {
	if x != nil {
		return x.AgentKey
	}
	return ""
}

func (x *RegisterHostResponse) GetCaCert() string {
	if x != nil {
		return x.CaCert
	}
	return ""
}

func (x *RegisterHostResponse) GetServerName() string {
	if x != nil {
		return x.ServerName
	}
	return ""
}

func (x *RegisterHostResponse) GetReactivated() bool {
	if x != nil {
		return x.Reactivated
	}
	return false
}

// HeartbeatRequest contains info sent with each heartbeat
type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`                // UUID of the host
	AgentKey      string                 `protobuf:"bytes,2,opt,name=agent_key,json=agentKey,proto3" json:"agent_key,omitempty"`             // Authentication key
	IpAddressV4   string                 `protobuf:"bytes,3,opt,name=ip_address_v4,json=ipAddressV4,proto3" json:"ip_address_v4,omitempty"`  // Current IPv4 (may change)
	IpAddressV6   string                 `protobuf:"bytes,4,opt,name=ip_address_v6,json=ipAddressV6,proto3" json:"ip_address_v6,omitempty"`  // Current IPv6 (may change)
	Timestamp     int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                          // Unix timestamp in seconds (for anti-replay)
	AgentVersion  string                 `protobuf:"bytes,6,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"` // Agent binary version, used to update DB immediately after self-update
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_agent_v1_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{2}
}

func (x *HeartbeatRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *HeartbeatRequest) GetAgentKey() string {
	if x != nil {
		return x.AgentKey
	}
	return ""
}

func (x *HeartbeatRequest) GetIpAddressV4() string {
	if x != nil {
		return x.IpAddressV4
	}
	return ""
}

func (x *HeartbeatRequest) GetIpAddressV6() string {
	if x != nil {
		return x.IpAddressV6
	}
	return ""
}

func (x *HeartbeatRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *HeartbeatRequest) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

// HeartbeatResponse acknowledges the heartbeat and may carry pending commands
type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Commands      []*PendingCommand      `protobuf:"bytes,3,rep,name=commands,proto3" json:"commands,omitempty"` // Commands to execute (empty if none)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_agent_v1_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{3}
}

func (x *HeartbeatResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *HeartbeatResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *HeartbeatResponse) GetCommands() []*PendingCommand {
	if x != nil {
		return x.Commands
	}
	return nil
}

// PendingCommand represents a command dispatched from the backend to the agent
type PendingCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"` // UUID for deduplication
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`                            // "collect_packages" | "update_agent"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PendingCommand) Reset() {
	*x = PendingCommand{}
	mi := &file_agent_v1_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PendingCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PendingCommand) ProtoMessage() {}

func (x *PendingCommand) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PendingCommand.ProtoReflect.Descriptor instead.
func (*PendingCommand) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{4}
}

func (x *PendingCommand) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *PendingCommand) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

// Metrics contains system performance data
type Metrics struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	CpuUsagePercent      float64                `protobuf:"fixed64,1,opt,name=cpu_usage_percent,json=cpuUsagePercent,proto3" json:"cpu_usage_percent,omitempty"`
	MemoryTotalBytes     uint64                 `protobuf:"varint,2,opt,name=memory_total_bytes,json=memoryTotalBytes,proto3" json:"memory_total_bytes,omitempty"`
	MemoryUsedBytes      uint64                 `protobuf:"varint,3,opt,name=memory_used_bytes,json=memoryUsedBytes,proto3" json:"memory_used_bytes,omitempty"`
	MemoryAvailableBytes uint64                 `protobuf:"varint,4,opt,name=memory_available_bytes,json=memoryAvailableBytes,proto3" json:"memory_available_bytes,omitempty"`
	LoadAvg_1Min         float64                `protobuf:"fixed64,5,opt,name=load_avg_1min,json=loadAvg1min,proto3" json:"load_avg_1min,omitempty"`
	LoadAvg_5Min         float64                `protobuf:"fixed64,6,opt,name=load_avg_5min,json=loadAvg5min,proto3" json:"load_avg_5min,omitempty"`
	LoadAvg_15Min        float64                `protobuf:"fixed64,7,opt,name=load_avg_15min,json=loadAvg15min,proto3" json:"load_avg_15min,omitempty"`
	DiskTotalBytes       uint64                 `protobuf:"varint,8,opt,name=disk_total_bytes,json=diskTotalBytes,proto3" json:"disk_total_bytes,omitempty"`
	DiskUsedBytes        uint64                 `protobuf:"varint,9,opt,name=disk_used_bytes,json=diskUsedBytes,proto3" json:"disk_used_bytes,omitempty"`
	UptimeSeconds        uint64                 `protobuf:"varint,10,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	Timestamp            int64                  `protobuf:"varint,11,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // Unix timestamp
	// Disk I/O metrics (bytes per second, computed from delta)
	DiskReadBytesPerSec  uint64 `protobuf:"varint,12,opt,name=disk_read_bytes_per_sec,json=diskReadBytesPerSec,proto3" json:"disk_read_bytes_per_sec,omitempty"`
	DiskWriteBytesPerSec uint64 `protobuf:"varint,13,opt,name=disk_write_bytes_per_sec,json=diskWriteBytesPerSec,proto3" json:"disk_write_bytes_per_sec,omitempty"`
	// Network metrics (bytes per second, computed from delta)
	NetworkRxBytesPerSec uint64 `protobuf:"varint,14,opt,name=network_rx_bytes_per_sec,json=networkRxBytesPerSec,proto3" json:"network_rx_bytes_per_sec,omitempty"`
	NetworkTxBytesPerSec uint64 `protobuf:"varint,15,opt,name=network_tx_bytes_per_sec,json=networkTxBytesPerSec,proto3" json:"network_tx_bytes_per_sec,omitempty"`
	// Temperature (physical servers only, 0 if unavailable)
	CpuTemperatureCelsius float64 `protobuf:"fixed64,16,opt,name=cpu_temperature_celsius,json=cpuTemperatureCelsius,proto3" json:"cpu_temperature_celsius,omitempty"`
	// All temperature sensor readings (one entry per sensor key)
	SensorReadings []*SensorReading `protobuf:"bytes,17,rep,name=sensor_readings,json=sensorReadings,proto3" json:"sensor_readings,omitempty"`
	// Swap memory
	SwapTotalBytes uint64 `protobuf:"varint,18,opt,name=swap_total_bytes,json=swapTotalBytes,proto3" json:"swap_total_bytes,omitempty"`
	SwapUsedBytes  uint64 `protobuf:"varint,19,opt,name=swap_used_bytes,json=swapUsedBytes,proto3" json:"swap_used_bytes,omitempty"`
	// Process count
	ProcessesCount uint64 `protobuf:"varint,20,opt,name=processes_count,json=processesCount,proto3" json:"processes_count,omitempty"`
	// Memory breakdown (Linux only, 0 on other platforms)
	MemoryBuffersBytes uint64 `protobuf:"varint,21,opt,name=memory_buffers_bytes,json=memoryBuffersBytes,proto3" json:"memory_buffers_bytes,omitempty"` // Kernel buffer cache
	MemoryCachedBytes  uint64 `protobuf:"varint,22,opt,name=memory_cached_bytes,json=memoryCachedBytes,proto3" json:"memory_cached_bytes,omitempty"`    // Page cache
	// CPU time breakdown (Linux only, 0 on other platforms)
	CpuIowaitPercent float64 `protobuf:"fixed64,23,opt,name=cpu_iowait_percent,json=cpuIowaitPercent,proto3" json:"cpu_iowait_percent,omitempty"` // Waiting for I/O completion
	CpuStealPercent  float64 `protobuf:"fixed64,24,opt,name=cpu_steal_percent,json=cpuStealPercent,proto3" json:"cpu_steal_percent,omitempty"`    // CPU stolen by hypervisor (VMs only)
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Metrics) Reset() {
	*x = Metrics{}
	mi := &file_agent_v1_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metrics) ProtoMessage() {}

func (x *Metrics) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metrics.ProtoReflect.Descriptor instead.
func (*Metrics) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{5}
}

func (x *Metrics) GetCpuUsagePercent() float64 {
	if x != nil {
		return x.CpuUsagePercent
	}
	return 0
}

func (x *Metrics) GetMemoryTotalBytes() uint64 {
	if x != nil {
		return x.MemoryTotalBytes
	}
	return 0
}

func (x *Metrics) GetMemoryUsedBytes() uint64 {
	if x != nil {
		return x.MemoryUsedBytes
	}
	return 0
}

func (x *Metrics) GetMemoryAvailableBytes() uint64 {
	if x != nil {
		return x.MemoryAvailableBytes
	}
	return 0
}

func (x *Metrics) GetLoadAvg_1Min() float64 {
	if x != nil {
		return x.LoadAvg_1Min
	}
	return 0
}

func (x *Metrics) GetLoadAvg_5Min() float64 {
	if x != nil {
		return x.LoadAvg_5Min
	}
	return 0
}

func (x *Metrics) GetLoadAvg_15Min() float64 {
	if x != nil {
		return x.LoadAvg_15Min
	}
	return 0
}

func (x *Metrics) GetDiskTotalBytes() uint64 {
	if x != nil {
		return x.DiskTotalBytes
	}
	return 0
}

func (x *Metrics) GetDiskUsedBytes() uint64 {
	if x != nil {
		return x.DiskUsedBytes
	}
	return 0
}

func (x *Metrics) GetUptimeSeconds() uint64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *Metrics) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Metrics) GetDiskReadBytesPerSec() uint64 {
	if x != nil {
		return x.DiskReadBytesPerSec
	}
	return 0
}

func (x *Metrics) GetDiskWriteBytesPerSec() uint64 {
	if x != nil {
		return x.DiskWriteBytesPerSec
	}
	return 0
}

func (x *Metrics) GetNetworkRxBytesPerSec() uint64 {
	if x != nil {
		return x.NetworkRxBytesPerSec
	}
	return 0
}

func (x *Metrics) GetNetworkTxBytesPerSec() uint64 {
	if x != nil {
		return x.NetworkTxBytesPerSec
	}
	return 0
}

func (x *Metrics) GetCpuTemperatureCelsius() float64 {
	if x != nil {
		return x.CpuTemperatureCelsius
	}
	return 0
}

func (x *Metrics) GetSensorReadings() []*SensorReading {
	if x != nil {
		return x.SensorReadings
	}
	return nil
}

func (x *Metrics) GetSwapTotalBytes() uint64 {
	if x != nil {
		return x.SwapTotalBytes
	}
	return 0
}

func (x *Metrics) GetSwapUsedBytes() uint64 {
	if x != nil {
		return x.SwapUsedBytes
	}
	return 0
}

func (x *Metrics) GetProcessesCount() uint64 {
	if x != nil {
		return x.ProcessesCount
	}
	return 0
}

func (x *Metrics) GetMemoryBuffersBytes() uint64 {
	if x != nil {
		return x.MemoryBuffersBytes
	}
	return 0
}

func (x *Metrics) GetMemoryCachedBytes() uint64 {
	if x != nil {
		return x.MemoryCachedBytes
	}
	return 0
}

func (x *Metrics) GetCpuIowaitPercent() float64 {
	if x != nil {
		return x.CpuIowaitPercent
	}
	return 0
}

func (x *Metrics) GetCpuStealPercent() float64 {
	if x != nil {
		return x.CpuStealPercent
	}
	return 0
}

// SensorReading represents a single temperature sensor reading
type SensorReading struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Key                string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`                                                           // Sensor key (e.g., "PMU tdie1", "NAND CH0 temp")
	TemperatureCelsius float64                `protobuf:"fixed64,2,opt,name=temperature_celsius,json=temperatureCelsius,proto3" json:"temperature_celsius,omitempty"` // Temperature in Celsius
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SensorReading) Reset() {
	*x = SensorReading{}
	mi := &file_agent_v1_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SensorReading) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SensorReading) ProtoMessage() {}

func (x *SensorReading) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SensorReading.ProtoReflect.Descriptor instead.
func (*SensorReading) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{6}
}

func (x *SensorReading) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SensorReading) GetTemperatureCelsius() float64 {
	if x != nil {
		return x.TemperatureCelsius
	}
	return 0
}

// ContainerMetric contains per-container performance data
type ContainerMetric struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	ContainerId          string                 `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	ContainerName        string                 `protobuf:"bytes,2,opt,name=container_name,json=containerName,proto3" json:"container_name,omitempty"`
	Image                string                 `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	CpuPercent           float64                `protobuf:"fixed64,4,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`
	MemoryUsedBytes      uint64                 `protobuf:"varint,5,opt,name=memory_used_bytes,json=memoryUsedBytes,proto3" json:"memory_used_bytes,omitempty"`
	MemoryLimitBytes     uint64                 `protobuf:"varint,6,opt,name=memory_limit_bytes,json=memoryLimitBytes,proto3" json:"memory_limit_bytes,omitempty"`
	NetworkRxBytesPerSec uint64                 `protobuf:"varint,7,opt,name=network_rx_bytes_per_sec,json=networkRxBytesPerSec,proto3" json:"network_rx_bytes_per_sec,omitempty"`
	NetworkTxBytesPerSec uint64                 `protobuf:"varint,8,opt,name=network_tx_bytes_per_sec,json=networkTxBytesPerSec,proto3" json:"network_tx_bytes_per_sec,omitempty"`
	ContainerRuntime     string                 `protobuf:"bytes,9,opt,name=container_runtime,json=containerRuntime,proto3" json:"container_runtime,omitempty"` // "docker", "podman", etc.
	Status               string                 `protobuf:"bytes,10,opt,name=status,proto3" json:"status,omitempty"`                                            // e.g. "Up 2 hours", "Restarting (1) 23 seconds ago"
	Health               string                 `protobuf:"bytes,11,opt,name=health,proto3" json:"health,omitempty"`                                            // "healthy", "unhealthy", "starting", "" (no healthcheck)
	Ports                string                 `protobuf:"bytes,12,opt,name=ports,proto3" json:"ports,omitempty"`                                              // e.g. "8080:80/tcp, 443:443/tcp"
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ContainerMetric) Reset() {
	*x = ContainerMetric{}
	mi := &file_agent_v1_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerMetric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerMetric) ProtoMessage() {}

func (x *ContainerMetric) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerMetric.ProtoReflect.Descriptor instead.
func (*ContainerMetric) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{7}
}

func (x *ContainerMetric) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *ContainerMetric) GetContainerName() string {
	if x != nil {
		return x.ContainerName
	}
	return ""
}

func (x *ContainerMetric) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *ContainerMetric) GetCpuPercent() float64 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *ContainerMetric) GetMemoryUsedBytes() uint64 {
	if x != nil {
		return x.MemoryUsedBytes
	}
	return 0
}

func (x *ContainerMetric) GetMemoryLimitBytes() uint64 {
	if x != nil {
		return x.MemoryLimitBytes
	}
	return 0
}

func (x *ContainerMetric) GetNetworkRxBytesPerSec() uint64 {
	if x != nil {
		return x.NetworkRxBytesPerSec
	}
	return 0
}

func (x *ContainerMetric) GetNetworkTxBytesPerSec() uint64 {
	if x != nil {
		return x.NetworkTxBytesPerSec
	}
	return 0
}

func (x *ContainerMetric) GetContainerRuntime() string {
	if x != nil {
		return x.ContainerRuntime
	}
	return ""
}

func (x *ContainerMetric) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ContainerMetric) GetHealth() string {
	if x != nil {
		return x.Health
	}
	return ""
}

func (x *ContainerMetric) GetPorts() string {
	if x != nil {
		return x.Ports
	}
	return ""
}

// HostInfo contains slowly-changing host properties sent with every metrics cycle.
// The backend only writes to DB if at least one field has changed.
type HostInfo struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PlatformVersion  string                 `protobuf:"bytes,1,opt,name=platform_version,json=platformVersion,proto3" json:"platform_version,omitempty"`       // gopsutil PlatformVersion: "43", "22.04"
	KernelVersion    string                 `protobuf:"bytes,2,opt,name=kernel_version,json=kernelVersion,proto3" json:"kernel_version,omitempty"`             // gopsutil KernelVersion: "6.17.1-300.fc43.aarch64"
	KernelArch       string                 `protobuf:"bytes,3,opt,name=kernel_arch,json=kernelArch,proto3" json:"kernel_arch,omitempty"`                      // gopsutil KernelArch: "x86_64", "aarch64"
	CpuModelName     string                 `protobuf:"bytes,4,opt,name=cpu_model_name,json=cpuModelName,proto3" json:"cpu_model_name,omitempty"`              // gopsutil cpu.InfoStat.ModelName
	CpuPhysicalCount int32                  `protobuf:"varint,5,opt,name=cpu_physical_count,json=cpuPhysicalCount,proto3" json:"cpu_physical_count,omitempty"` // gopsutil cpu.Counts(false)
	CpuLogicalCount  int32                  `protobuf:"varint,6,opt,name=cpu_logical_count,json=cpuLogicalCount,proto3" json:"cpu_logical_count,omitempty"`    // gopsutil cpu.Counts(true)
	CpuMhz           float64                `protobuf:"fixed64,7,opt,name=cpu_mhz,json=cpuMhz,proto3" json:"cpu_mhz,omitempty"`                                // gopsutil cpu.InfoStat.Mhz
	ContainerRuntime string                 `protobuf:"bytes,8,opt,name=container_runtime,json=containerRuntime,proto3" json:"container_runtime,omitempty"`    // "docker", "kubernetes", etc. (empty if not in container)
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *HostInfo) Reset() {
	*x = HostInfo{}
	mi := &file_agent_v1_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostInfo) ProtoMessage() {}

func (x *HostInfo) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostInfo.ProtoReflect.Descriptor instead.
func (*HostInfo) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{8}
}

func (x *HostInfo) GetPlatformVersion() string {
	if x != nil {
		return x.PlatformVersion
	}
	return ""
}

func (x *HostInfo) GetKernelVersion() string {
	if x != nil {
		return x.KernelVersion
	}
	return ""
}

func (x *HostInfo) GetKernelArch() string {
	if x != nil {
		return x.KernelArch
	}
	return ""
}

func (x *HostInfo) GetCpuModelName() string {
	if x != nil {
		return x.CpuModelName
	}
	return ""
}

func (x *HostInfo) GetCpuPhysicalCount() int32 {
	if x != nil {
		return x.CpuPhysicalCount
	}
	return 0
}

func (x *HostInfo) GetCpuLogicalCount() int32 {
	if x != nil {
		return x.CpuLogicalCount
	}
	return 0
}

func (x *HostInfo) GetCpuMhz() float64 {
	if x != nil {
		return x.CpuMhz
	}
	return 0
}

func (x *HostInfo) GetContainerRuntime() string {
	if x != nil {
		return x.ContainerRuntime
	}
	return ""
}

// SendMetricsRequest contains authentication and metrics data
type SendMetricsRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AgentId          string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`                            // UUID of the host
	AgentKey         string                 `protobuf:"bytes,2,opt,name=agent_key,json=agentKey,proto3" json:"agent_key,omitempty"`                         // Authentication key
	Metrics          *Metrics               `protobuf:"bytes,3,opt,name=metrics,proto3" json:"metrics,omitempty"`                                           // System metrics
	Timestamp        int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                                      // Unix timestamp in seconds (for anti-replay)
	ContainerMetrics []*ContainerMetric     `protobuf:"bytes,5,rep,name=container_metrics,json=containerMetrics,proto3" json:"container_metrics,omitempty"` // Per-container metrics (empty if no containers)
	AgentVersion     string                 `protobuf:"bytes,6,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`             // Agent binary version, sent to keep DB in sync after upgrades
	HostInfo         *HostInfo              `protobuf:"bytes,7,opt,name=host_info,json=hostInfo,proto3" json:"host_info,omitempty"`                         // Slowly-changing host properties, updated only on change
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SendMetricsRequest) Reset() {
	*x = SendMetricsRequest{}
	mi := &file_agent_v1_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMetricsRequest) ProtoMessage() {}

func (x *SendMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMetricsRequest.ProtoReflect.Descriptor instead.
func (*SendMetricsRequest) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{9}
}

func (x *SendMetricsRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *SendMetricsRequest) GetAgentKey() string {
	if x != nil {
		return x.AgentKey
	}
	return ""
}

func (x *SendMetricsRequest) GetMetrics() *Metrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *SendMetricsRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *SendMetricsRequest) GetContainerMetrics() []*ContainerMetric {
	if x != nil {
		return x.ContainerMetrics
	}
	return nil
}

func (x *SendMetricsRequest) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *SendMetricsRequest) GetHostInfo() *HostInfo {
	if x != nil {
		return x.HostInfo
	}
	return nil
}

// SendMetricsResponse acknowledges metric reception
type SendMetricsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMetricsResponse) Reset() {
	*x = SendMetricsResponse{}
	mi := &file_agent_v1_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMetricsResponse) ProtoMessage() {}

func (x *SendMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMetricsResponse.ProtoReflect.Descriptor instead.
func (*SendMetricsResponse) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{10}
}

func (x *SendMetricsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SendMetricsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// BufferedMetric represents a metric stored in the WAL buffer
// This message is used for disk serialization, NOT for gRPC transport
type BufferedMetric struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`              // UUID of the agent
	AgentKey      string                 `protobuf:"bytes,2,opt,name=agent_key,json=agentKey,proto3" json:"agent_key,omitempty"`           // Authentication key
	Metrics       *Metrics               `protobuf:"bytes,3,opt,name=metrics,proto3" json:"metrics,omitempty"`                             // System metrics
	CollectedAt   int64                  `protobuf:"varint,4,opt,name=collected_at,json=collectedAt,proto3" json:"collected_at,omitempty"` // Unix timestamp when metric was collected
	RetryCount    uint32                 `protobuf:"varint,5,opt,name=retry_count,json=retryCount,proto3" json:"retry_count,omitempty"`    // Number of retry attempts (0 = first attempt)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BufferedMetric) Reset() {
	*x = BufferedMetric{}
	mi := &file_agent_v1_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BufferedMetric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BufferedMetric) ProtoMessage() {}

func (x *BufferedMetric) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BufferedMetric.ProtoReflect.Descriptor instead.
func (*BufferedMetric) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{11}
}

func (x *BufferedMetric) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *BufferedMetric) GetAgentKey() string {
	if x != nil {
		return x.AgentKey
	}
	return ""
}

func (x *BufferedMetric) GetMetrics() *Metrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *BufferedMetric) GetCollectedAt() int64 {
	if x != nil {
		return x.CollectedAt
	}
	return 0
}

func (x *BufferedMetric) GetRetryCount() uint32 {
	if x != nil {
		return x.RetryCount
	}
	return 0
}

// ReportDroppedMetricsRequest contains information about metrics that were dropped
type ReportDroppedMetricsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AgentId        string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`                         // UUID of the agent
	AgentKey       string                 `protobuf:"bytes,2,opt,name=agent_key,json=agentKey,proto3" json:"agent_key,omitempty"`                      // Authentication key
	Timestamp      int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                                   // Unix timestamp when report was sent
	Count          int32                  `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`                                           // Number of metrics dropped
	FirstDroppedAt int64                  `protobuf:"varint,5,opt,name=first_dropped_at,json=firstDroppedAt,proto3" json:"first_dropped_at,omitempty"` // Timestamp of first dropped metric
	LastDroppedAt  int64                  `protobuf:"varint,6,opt,name=last_dropped_at,json=lastDroppedAt,proto3" json:"last_dropped_at,omitempty"`    // Timestamp of last dropped metric
	Reason         string                 `protobuf:"bytes,7,opt,name=reason,proto3" json:"reason,omitempty"`                                          // Reason for dropping (e.g., "max_retries_exceeded")
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReportDroppedMetricsRequest) Reset() {
	*x = ReportDroppedMetricsRequest{}
	mi := &file_agent_v1_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportDroppedMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportDroppedMetricsRequest) ProtoMessage() {}

func (x *ReportDroppedMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportDroppedMetricsRequest.ProtoReflect.Descriptor instead.
func (*ReportDroppedMetricsRequest) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{12}
}

func (x *ReportDroppedMetricsRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *ReportDroppedMetricsRequest) GetAgentKey() string {
	if x != nil {
		return x.AgentKey
	}
	return ""
}

func (x *ReportDroppedMetricsRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ReportDroppedMetricsRequest) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *ReportDroppedMetricsRequest) GetFirstDroppedAt() int64 {
	if x != nil {
		return x.FirstDroppedAt
	}
	return 0
}

func (x *ReportDroppedMetricsRequest) GetLastDroppedAt() int64 {
	if x != nil {
		return x.LastDroppedAt
	}
	return 0
}

func (x *ReportDroppedMetricsRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// ReportDroppedMetricsResponse acknowledges the dropped metrics report
type ReportDroppedMetricsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportDroppedMetricsResponse) Reset() {
	*x = ReportDroppedMetricsResponse{}
	mi := &file_agent_v1_agent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportDroppedMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportDroppedMetricsResponse) ProtoMessage() {}

func (x *ReportDroppedMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportDroppedMetricsResponse.ProtoReflect.Descriptor instead.
func (*ReportDroppedMetricsResponse) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{13}
}

func (x *ReportDroppedMetricsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReportDroppedMetricsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Package represents a single installed package
type Package struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Name              string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                                                        // Package name (e.g., "nginx", "postgresql-15")
	Version           string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`                                                  // Version string (e.g., "1.24.0-1", "15.4-1")
	Architecture      string                 `protobuf:"bytes,3,opt,name=architecture,proto3" json:"architecture,omitempty"`                                        // Architecture (e.g., "amd64", "arm64", "all")
	PackageManager    string                 `protobuf:"bytes,4,opt,name=package_manager,json=packageManager,proto3" json:"package_manager,omitempty"`              // Package manager type (e.g., "dpkg", "rpm", "brew")
	Source            string                 `protobuf:"bytes,5,opt,name=source,proto3" json:"source,omitempty"`                                                    // Repository or source URL
	InstalledAt       int64                  `protobuf:"varint,6,opt,name=installed_at,json=installedAt,proto3" json:"installed_at,omitempty"`                      // Unix timestamp of installation (0 if unknown)
	PackageSize       int64                  `protobuf:"varint,7,opt,name=package_size,json=packageSize,proto3" json:"package_size,omitempty"`                      // Package size in bytes
	Description       string                 `protobuf:"bytes,8,opt,name=description,proto3" json:"description,omitempty"`                                          // Short description (max 100 chars)
	AvailableVersion  string                 `protobuf:"bytes,9,opt,name=available_version,json=availableVersion,proto3" json:"available_version,omitempty"`        // Newer version available (empty if up to date)
	HasSecurityUpdate bool                   `protobuf:"varint,10,opt,name=has_security_update,json=hasSecurityUpdate,proto3" json:"has_security_update,omitempty"` // True if available_version is a security update
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Package) Reset() {
	*x = Package{}
	mi := &file_agent_v1_agent_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Package) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Package) ProtoMessage() {}

func (x *Package) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Package.ProtoReflect.Descriptor instead.
func (*Package) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{14}
}

func (x *Package) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Package) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Package) GetArchitecture() string {
	if x != nil {
		return x.Architecture
	}
	return ""
}

func (x *Package) GetPackageManager() string {
	if x != nil {
		return x.PackageManager
	}
	return ""
}

func (x *Package) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Package) GetInstalledAt() int64 {
	if x != nil {
		return x.InstalledAt
	}
	return 0
}

func (x *Package) GetPackageSize() int64 {
	if x != nil {
		return x.PackageSize
	}
	return 0
}

func (x *Package) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Package) GetAvailableVersion() string {
	if x != nil {
		return x.AvailableVersion
	}
	return ""
}

func (x *Package) GetHasSecurityUpdate() bool {
	if x != nil {
		return x.HasSecurityUpdate
	}
	return false
}

// SendPackageInventoryRequest sends package inventory (delta or full) to backend
type SendPackageInventoryRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	AgentId   string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`    // UUID of the host
	AgentKey  string                 `protobuf:"bytes,2,opt,name=agent_key,json=agentKey,proto3" json:"agent_key,omitempty"` // Authentication key
	Timestamp int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`              // Request timestamp (for anti-replay)
	// Inventory type: "delta" or "full"
	// - "delta": Only sends changes (added/removed/updated)
	// - "full": Sends complete package list (used on first run or if state corrupted)
	InventoryType string `protobuf:"bytes,4,opt,name=inventory_type,json=inventoryType,proto3" json:"inventory_type,omitempty"`
	// Delta inventory (only populated if inventory_type = "delta")
	AddedPackages   []*Package `protobuf:"bytes,5,rep,name=added_packages,json=addedPackages,proto3" json:"added_packages,omitempty"`       // Newly installed packages
	RemovedPackages []*Package `protobuf:"bytes,6,rep,name=removed_packages,json=removedPackages,proto3" json:"removed_packages,omitempty"` // Uninstalled packages
	UpdatedPackages []*Package `protobuf:"bytes,7,rep,name=updated_packages,json=updatedPackages,proto3" json:"updated_packages,omitempty"` // Packages with version changes
	// Full inventory (only populated if inventory_type = "full")
	AllPackages []*Package `protobuf:"bytes,8,rep,name=all_packages,json=allPackages,proto3" json:"all_packages,omitempty"` // Complete package list
	// Collection metadata
	CollectionDurationMs int64 `protobuf:"varint,9,opt,name=collection_duration_ms,json=collectionDurationMs,proto3" json:"collection_duration_ms,omitempty"` // Time taken to collect packages (milliseconds)
	TotalPackageCount    int32 `protobuf:"varint,10,opt,name=total_package_count,json=totalPackageCount,proto3" json:"total_package_count,omitempty"`         // Total number of packages on system
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *SendPackageInventoryRequest) Reset() {
	*x = SendPackageInventoryRequest{}
	mi := &file_agent_v1_agent_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendPackageInventoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendPackageInventoryRequest) ProtoMessage() {}

func (x *SendPackageInventoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendPackageInventoryRequest.ProtoReflect.Descriptor instead.
func (*SendPackageInventoryRequest) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{15}
}

func (x *SendPackageInventoryRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *SendPackageInventoryRequest) GetAgentKey() string {
	if x != nil {
		return x.AgentKey
	}
	return ""
}

func (x *SendPackageInventoryRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *SendPackageInventoryRequest) GetInventoryType() string {
	if x != nil {
		return x.InventoryType
	}
	return ""
}

func (x *SendPackageInventoryRequest) GetAddedPackages() []*Package {
	if x != nil {
		return x.AddedPackages
	}
	return nil
}

func (x *SendPackageInventoryRequest) GetRemovedPackages() []*Package {
	if x != nil {
		return x.RemovedPackages
	}
	return nil
}

func (x *SendPackageInventoryRequest) GetUpdatedPackages() []*Package {
	if x != nil {
		return x.UpdatedPackages
	}
	return nil
}

func (x *SendPackageInventoryRequest) GetAllPackages() []*Package {
	if x != nil {
		return x.AllPackages
	}
	return nil
}

func (x *SendPackageInventoryRequest) GetCollectionDurationMs() int64 {
	if x != nil {
		return x.CollectionDurationMs
	}
	return 0
}

func (x *SendPackageInventoryRequest) GetTotalPackageCount() int32 {
	if x != nil {
		return x.TotalPackageCount
	}
	return 0
}

// SendPackageInventoryResponse acknowledges inventory reception
type SendPackageInventoryResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Success           bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message           string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	PackagesProcessed int32                  `protobuf:"varint,3,opt,name=packages_processed,json=packagesProcessed,proto3" json:"packages_processed,omitempty"` // Number of packages processed
	ChangesDetected   int32                  `protobuf:"varint,4,opt,name=changes_detected,json=changesDetected,proto3" json:"changes_detected,omitempty"`       // Number of changes detected (added+removed+updated)
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SendPackageInventoryResponse) Reset() {
	*x = SendPackageInventoryResponse{}
	mi := &file_agent_v1_agent_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendPackageInventoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendPackageInventoryResponse) ProtoMessage() {}

func (x *SendPackageInventoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendPackageInventoryResponse.ProtoReflect.Descriptor instead.
func (*SendPackageInventoryResponse) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{16}
}

func (x *SendPackageInventoryResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SendPackageInventoryResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SendPackageInventoryResponse) GetPackagesProcessed() int32 {
	if x != nil {
		return x.PackagesProcessed
	}
	return 0
}

func (x *SendPackageInventoryResponse) GetChangesDetected() int32 {
	if x != nil {
		return x.ChangesDetected
	}
	return 0
}

var File_agent_v1_agent_proto protoreflect.FileDescriptor

const file_agent_v1_agent_proto_rawDesc = "" +
	"\n" +
	"\x14agent/v1/agent.proto\x12\bagent.v1\"\xd3\x06\n" +
	"\x13RegisterHostRequest\x12-\n" +
	"\x12registration_token\x18\x01 \x01(\tR\x11registrationToken\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\"\n" +
	"\rip_address_v4\x18\x03 \x01(\tR\vipAddressV4\x12\"\n" +
	"\rip_address_v6\x18\x04 \x01(\tR\vipAddressV6\x12\x1a\n" +
	"\bplatform\x18\x05 \x01(\tR\bplatform\x12)\n" +
	"\x10platform_version\x18\x06 \x01(\tR\x0fplatformVersion\x12'\n" +
	"\x0fplatform_family\x18\a \x01(\tR\x0eplatformFamily\x12\x1f\n" +
	"\vkernel_arch\x18\b \x01(\tR\n" +
	"kernelArch\x12%\n" +
	"\x0ekernel_version\x18\t \x01(\tR\rkernelVersion\x12\x1c\n" +
	"\ttimestamp\x18\n" +
	" \x01(\x03R\ttimestamp\x12)\n" +
	"\x10environment_type\x18\v \x01(\tR\x0fenvironmentType\x123\n" +
	"\x15virtualization_system\x18\f \x01(\tR\x14virtualizationSystem\x12+\n" +
	"\x11container_runtime\x18\r \x01(\tR\x10containerRuntime\x12.\n" +
	"\x13existing_agent_uuid\x18\x0e \x01(\tR\x11existingAgentUuid\x12#\n" +
	"\ragent_version\x18\x0f \x01(\tR\fagentVersion\x12\x0e\n" +
	"\x02os\x18\x10 \x01(\tR\x02os\x12/\n" +
	"\x13virtualization_role\x18\x11 \x01(\tR\x12virtualizationRole\x12\x17\n" +
	"\ahost_id\x18\x12 \x01(\tR\x06hostId\x12$\n" +
	"\x0ecpu_model_name\x18\x13 \x01(\tR\fcpuModelName\x12,\n" +
	"\x12cpu_physical_count\x18\x14 \x01(\x05R\x10cpuPhysicalCount\x12*\n" +
	"\x11cpu_logical_count\x18\x15 \x01(\x05R\x0fcpuLogicalCount\x12\x17\n" +
	"\acpu_mhz\x18\x16 \x01(\x01R\x06cpuMhz\"\xde\x01\n" +
	"\x14RegisterHostResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x19\n" +
	"\bagent_id\x18\x03 \x01(\tR\aagentId\x12\x1b\n" +
	"\tagent_key\x18\x04 \x01(\tR\bagentKey\x12\x17\n" +
	"\aca_cert\x18\x05 \x01(\tR\x06caCert\x12\x1f\n" +
	"\vserver_name\x18\x06 \x01(\tR\n" +
	"serverName\x12 \n" +
	"\vreactivated\x18\a \x01(\bR\vreactivated\"\xd5\x01\n" +
	"\x10HeartbeatRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1b\n" +
	"\tagent_key\x18\x02 \x01(\tR\bagentKey\x12\"\n" +
	"\rip_address_v4\x18\x03 \x01(\tR\vipAddressV4\x12\"\n" +
	"\rip_address_v6\x18\x04 \x01(\tR\vipAddressV6\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\x12#\n" +
	"\ragent_version\x18\x06 \x01(\tR\fagentVersion\"}\n" +
	"\x11HeartbeatResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x124\n" +
	"\bcommands\x18\x03 \x03(\v2\x18.agent.v1.PendingCommandR\bcommands\"C\n" +
	"\x0ePendingCommand\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\"\xd9\b\n" +
	"\aMetrics\x12*\n" +
	"\x11cpu_usage_percent\x18\x01 \x01(\x01R\x0fcpuUsagePercent\x12,\n" +
	"\x12memory_total_bytes\x18\x02 \x01(\x04R\x10memoryTotalBytes\x12*\n" +
	"\x11memory_used_bytes\x18\x03 \x01(\x04R\x0fmemoryUsedBytes\x124\n" +
	"\x16memory_available_bytes\x18\x04 \x01(\x04R\x14memoryAvailableBytes\x12\"\n" +
	"\rload_avg_1min\x18\x05 \x01(\x01R\vloadAvg1min\x12\"\n" +
	"\rload_avg_5min\x18\x06 \x01(\x01R\vloadAvg5min\x12$\n" +
	"\x0eload_avg_15min\x18\a \x01(\x01R\floadAvg15min\x12(\n" +
	"\x10disk_total_bytes\x18\b \x01(\x04R\x0ediskTotalBytes\x12&\n" +
	"\x0fdisk_used_bytes\x18\t \x01(\x04R\rdiskUsedBytes\x12%\n" +
	"\x0euptime_seconds\x18\n" +
	" \x01(\x04R\ruptimeSeconds\x12\x1c\n" +
	"\ttimestamp\x18\v \x01(\x03R\ttimestamp\x124\n" +
	"\x17disk_read_bytes_per_sec\x18\f \x01(\x04R\x13diskReadBytesPerSec\x126\n" +
	"\x18disk_write_bytes_per_sec\x18\r \x01(\x04R\x14diskWriteBytesPerSec\x126\n" +
	"\x18network_rx_bytes_per_sec\x18\x0e \x01(\x04R\x14networkRxBytesPerSec\x126\n" +
	"\x18network_tx_bytes_per_sec\x18\x0f \x01(\x04R\x14networkTxBytesPerSec\x126\n" +
	"\x17cpu_temperature_celsius\x18\x10 \x01(\x01R\x15cpuTemperatureCelsius\x12@\n" +
	"\x0fsensor_readings\x18\x11 \x03(\v2\x17.agent.v1.SensorReadingR\x0esensorReadings\x12(\n" +
	"\x10swap_total_bytes\x18\x12 \x01(\x04R\x0eswapTotalBytes\x12&\n" +
	"\x0fswap_used_bytes\x18\x13 \x01(\x04R\rswapUsedBytes\x12'\n" +
	"\x0fprocesses_count\x18\x14 \x01(\x04R\x0eprocessesCount\x120\n" +
	"\x14memory_buffers_bytes\x18\x15 \x01(\x04R\x12memoryBuffersBytes\x12.\n" +
	"\x13memory_cached_bytes\x18\x16 \x01(\x04R\x11memoryCachedBytes\x12,\n" +
	"\x12cpu_iowait_percent\x18\x17 \x01(\x01R\x10cpuIowaitPercent\x12*\n" +
	"\x11cpu_steal_percent\x18\x18 \x01(\x01R\x0fcpuStealPercent\"R\n" +
	"\rSensorReading\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12/\n" +
	"\x13temperature_celsius\x18\x02 \x01(\x01R\x12temperatureCelsius\"\xcf\x03\n" +
	"\x0fContainerMetric\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\x12%\n" +
	"\x0econtainer_name\x18\x02 \x01(\tR\rcontainerName\x12\x14\n" +
	"\x05image\x18\x03 \x01(\tR\x05image\x12\x1f\n" +
	"\vcpu_percent\x18\x04 \x01(\x01R\n" +
	"cpuPercent\x12*\n" +
	"\x11memory_used_bytes\x18\x05 \x01(\x04R\x0fmemoryUsedBytes\x12,\n" +
	"\x12memory_limit_bytes\x18\x06 \x01(\x04R\x10memoryLimitBytes\x126\n" +
	"\x18network_rx_bytes_per_sec\x18\a \x01(\x04R\x14networkRxBytesPerSec\x126\n" +
	"\x18network_tx_bytes_per_sec\x18\b \x01(\x04R\x14networkTxBytesPerSec\x12+\n" +
	"\x11container_runtime\x18\t \x01(\tR\x10containerRuntime\x12\x16\n" +
	"\x06status\x18\n" +
	" \x01(\tR\x06status\x12\x16\n" +
	"\x06health\x18\v \x01(\tR\x06health\x12\x14\n" +
	"\x05ports\x18\f \x01(\tR\x05ports\"\xc3\x02\n" +
	"\bHostInfo\x12)\n" +
	"\x10platform_version\x18\x01 \x01(\tR\x0fplatformVersion\x12%\n" +
	"\x0ekernel_version\x18\x02 \x01(\tR\rkernelVersion\x12\x1f\n" +
	"\vkernel_arch\x18\x03 \x01(\tR\n" +
	"kernelArch\x12$\n" +
	"\x0ecpu_model_name\x18\x04 \x01(\tR\fcpuModelName\x12,\n" +
	"\x12cpu_physical_count\x18\x05 \x01(\x05R\x10cpuPhysicalCount\x12*\n" +
	"\x11cpu_logical_count\x18\x06 \x01(\x05R\x0fcpuLogicalCount\x12\x17\n" +
	"\acpu_mhz\x18\a \x01(\x01R\x06cpuMhz\x12+\n" +
	"\x11container_runtime\x18\b \x01(\tR\x10containerRuntime\"\xb5\x02\n" +
	"\x12SendMetricsRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1b\n" +
	"\tagent_key\x18\x02 \x01(\tR\bagentKey\x12+\n" +
	"\ametrics\x18\x03 \x01(\v2\x11.agent.v1.MetricsR\ametrics\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\x12F\n" +
	"\x11container_metrics\x18\x05 \x03(\v2\x19.agent.v1.ContainerMetricR\x10containerMetrics\x12#\n" +
	"\ragent_version\x18\x06 \x01(\tR\fagentVersion\x12/\n" +
	"\thost_info\x18\a \x01(\v2\x12.agent.v1.HostInfoR\bhostInfo\"I\n" +
	"\x13SendMetricsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xb9\x01\n" +
	"\x0eBufferedMetric\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1b\n" +
	"\tagent_key\x18\x02 \x01(\tR\bagentKey\x12+\n" +
	"\ametrics\x18\x03 \x01(\v2\x11.agent.v1.MetricsR\ametrics\x12!\n" +
	"\fcollected_at\x18\x04 \x01(\x03R\vcollectedAt\x12\x1f\n" +
	"\vretry_count\x18\x05 \x01(\rR\n" +
	"retryCount\"\xf3\x01\n" +
	"\x1bReportDroppedMetricsRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1b\n" +
	"\tagent_key\x18\x02 \x01(\tR\bagentKey\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x12\x14\n" +
	"\x05count\x18\x04 \x01(\x05R\x05count\x12(\n" +
	"\x10first_dropped_at\x18\x05 \x01(\x03R\x0efirstDroppedAt\x12&\n" +
	"\x0flast_dropped_at\x18\x06 \x01(\x03R\rlastDroppedAt\x12\x16\n" +
	"\x06reason\x18\a \x01(\tR\x06reason\"R\n" +
	"\x1cReportDroppedMetricsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xe1\x02\n" +
	"\aPackage\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\"\n" +
	"\farchitecture\x18\x03 \x01(\tR\farchitecture\x12'\n" +
	"\x0fpackage_manager\x18\x04 \x01(\tR\x0epackageManager\x12\x16\n" +
	"\x06source\x18\x05 \x01(\tR\x06source\x12!\n" +
	"\finstalled_at\x18\x06 \x01(\x03R\vinstalledAt\x12!\n" +
	"\fpackage_size\x18\a \x01(\x03R\vpackageSize\x12 \n" +
	"\vdescription\x18\b \x01(\tR\vdescription\x12+\n" +
	"\x11available_version\x18\t \x01(\tR\x10availableVersion\x12.\n" +
	"\x13has_security_update\x18\n" +
	" \x01(\bR\x11hasSecurityUpdate\"\xec\x03\n" +
	"\x1bSendPackageInventoryRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1b\n" +
	"\tagent_key\x18\x02 \x01(\tR\bagentKey\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x12%\n" +
	"\x0einventory_type\x18\x04 \x01(\tR\rinventoryType\x128\n" +
	"\x0eadded_packages\x18\x05 \x03(\v2\x11.agent.v1.PackageR\raddedPackages\x12<\n" +
	"\x10removed_packages\x18\x06 \x03(\v2\x11.agent.v1.PackageR\x0fremovedPackages\x12<\n" +
	"\x10updated_packages\x18\a \x03(\v2\x11.agent.v1.PackageR\x0fupdatedPackages\x124\n" +
	"\fall_packages\x18\b \x03(\v2\x11.agent.v1.PackageR\vallPackages\x124\n" +
	"\x16collection_duration_ms\x18\t \x01(\x03R\x14collectionDurationMs\x12.\n" +
	"\x13total_package_count\x18\n" +
	" \x01(\x05R\x11totalPackageCount\"\xac\x01\n" +
	"\x1cSendPackageInventoryResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12-\n" +
	"\x12packages_processed\x18\x03 \x01(\x05R\x11packagesProcessed\x12)\n" +
	"\x10changes_detected\x18\x04 \x01(\x05R\x0fchangesDetected2\xbd\x03\n" +
	"\fAgentService\x12M\n" +
	"\fRegisterHost\x12\x1d.agent.v1.RegisterHostRequest\x1a\x1e.agent.v1.RegisterHostResponse\x12D\n" +
	"\tHeartbeat\x12\x1a.agent.v1.HeartbeatRequest\x1a\x1b.agent.v1.HeartbeatResponse\x12J\n" +
	"\vSendMetrics\x12\x1c.agent.v1.SendMetricsRequest\x1a\x1d.agent.v1.SendMetricsResponse\x12e\n" +
	"\x14ReportDroppedMetrics\x12%.agent.v1.ReportDroppedMetricsRequest\x1a&.agent.v1.ReportDroppedMetricsResponse\x12e\n" +
	"\x14SendPackageInventory\x12%.agent.v1.SendPackageInventoryRequest\x1a&.agent.v1.SendPackageInventoryResponseB(Z&watchflare/shared/proto/agent/v1;protob\x06proto3"

var (
	file_agent_v1_agent_proto_rawDescOnce sync.Once
	file_agent_v1_agent_proto_rawDescData []byte
)

func file_agent_v1_agent_proto_rawDescGZIP() []byte {
	file_agent_v1_agent_proto_rawDescOnce.Do(func() {
		file_agent_v1_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_v1_agent_proto_rawDesc), len(file_agent_v1_agent_proto_rawDesc)))
	})
	return file_agent_v1_agent_proto_rawDescData
}

var file_agent_v1_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_agent_v1_agent_proto_goTypes = []any{
	(*RegisterHostRequest)(nil),          // 0: agent.v1.RegisterHostRequest
	(*RegisterHostResponse)(nil),         // 1: agent.v1.RegisterHostResponse
	(*HeartbeatRequest)(nil),             // 2: agent.v1.HeartbeatRequest
	(*HeartbeatResponse)(nil),            // 3: agent.v1.HeartbeatResponse
	(*PendingCommand)(nil),               // 4: agent.v1.PendingCommand
	(*Metrics)(nil),                      // 5: agent.v1.Metrics
	(*SensorReading)(nil),                // 6: agent.v1.SensorReading
	(*ContainerMetric)(nil),              // 7: agent.v1.ContainerMetric
	(*HostInfo)(nil),                     // 8: agent.v1.HostInfo
	(*SendMetricsRequest)(nil),           // 9: agent.v1.SendMetricsRequest
	(*SendMetricsResponse)(nil),          // 10: agent.v1.SendMetricsResponse
	(*BufferedMetric)(nil),               // 11: agent.v1.BufferedMetric
	(*ReportDroppedMetricsRequest)(nil),  // 12: agent.v1.ReportDroppedMetricsRequest
	(*ReportDroppedMetricsResponse)(nil), // 13: agent.v1.ReportDroppedMetricsResponse
	(*Package)(nil),                      // 14: agent.v1.Package
	(*SendPackageInventoryRequest)(nil),  // 15: agent.v1.SendPackageInventoryRequest
	(*SendPackageInventoryResponse)(nil), // 16: agent.v1.SendPackageInventoryResponse
}
var file_agent_v1_agent_proto_depIdxs = []int32{
	4,  // 0: agent.v1.HeartbeatResponse.commands:type_name -> agent.v1.PendingCommand
	6,  // 1: agent.v1.Metrics.sensor_readings:type_name -> agent.v1.SensorReading
	5,  // 2: agent.v1.SendMetricsRequest.metrics:type_name -> agent.v1.Metrics
	7,  // 3: agent.v1.SendMetricsRequest.container_metrics:type_name -> agent.v1.ContainerMetric
	8,  // 4: agent.v1.SendMetricsRequest.host_info:type_name -> agent.v1.HostInfo
	5,  // 5: agent.v1.BufferedMetric.metrics:type_name -> agent.v1.Metrics
	14, // 6: agent.v1.SendPackageInventoryRequest.added_packages:type_name -> agent.v1.Package
	14, // 7: agent.v1.SendPackageInventoryRequest.removed_packages:type_name -> agent.v1.Package
	14, // 8: agent.v1.SendPackageInventoryRequest.updated_packages:type_name -> agent.v1.Package
	14, // 9: agent.v1.SendPackageInventoryRequest.all_packages:type_name -> agent.v1.Package
	0,  // 10: agent.v1.AgentService.RegisterHost:input_type -> agent.v1.RegisterHostRequest
	2,  // 11: agent.v1.AgentService.Heartbeat:input_type -> agent.v1.HeartbeatRequest
	9,  // 12: agent.v1.AgentService.SendMetrics:input_type -> agent.v1.SendMetricsRequest
	12, // 13: agent.v1.AgentService.ReportDroppedMetrics:input_type -> agent.v1.ReportDroppedMetricsRequest
	15, // 14: agent.v1.AgentService.SendPackageInventory:input_type -> agent.v1.SendPackageInventoryRequest
	1,  // 15: agent.v1.AgentService.RegisterHost:output_type -> agent.v1.RegisterHostResponse
	3,  // 16: agent.v1.AgentService.Heartbeat:output_type -> agent.v1.HeartbeatResponse
	10, // 17: agent.v1.AgentService.SendMetrics:output_type -> agent.v1.SendMetricsResponse
	13, // 18: agent.v1.AgentService.ReportDroppedMetrics:output_type -> agent.v1.ReportDroppedMetricsResponse
	16, // 19: agent.v1.AgentService.SendPackageInventory:output_type -> agent.v1.SendPackageInventoryResponse
	15, // [15:20] is the sub-list for method output_type
	10, // [10:15] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_agent_v1_agent_proto_init() }
func file_agent_v1_agent_proto_init() {
	if File_agent_v1_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_v1_agent_proto_rawDesc), len(file_agent_v1_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agent_v1_agent_proto_goTypes,
		DependencyIndexes: file_agent_v1_agent_proto_depIdxs,
		MessageInfos:      file_agent_v1_agent_proto_msgTypes,
	}.Build()
	File_agent_v1_agent_proto = out.File
	file_agent_v1_agent_proto_goTypes = nil
	file_agent_v1_agent_proto_depIdxs = nil
}
